default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: manyoukadai_development
test:
  <<: *default
  database: manyoukadai_test
production:
  <<: *default
  database: manyoukadai_production
  username: manyoukadai
  password: <%= ENV['MANYOUKADAI_DATABASE_PASSWORD'] %>
